DrylandEcology/SOILWAT2

- SW_Flow.c
- SW_Flow_lib.c
- SW_Flow_lib.h
- SW_Output.c
- SW_Output.h
- SW_R_lib.c
- SW_Site.c
- SW_SoilWater.h
These changes coincide with the modifications in the Soilwat_R_Wrapper repository to account for soil temperature errors based on matric density values.
-There is not implementation to modify soil temperature values in the case of an error, but there is a flag that checks for soil temperature errors
-The flag can then be checked in R through the wrapper
Author:
@charlieduso
> Soil temp error branch

- .gitignore
- README.md
- appveyor.yml
- improve ci
- improve status updates on readme
> Feature CodeTesting

- .gitignore
- .gitmodules
- README.md
- makefile
- test/sw_test.cc
Unit testing framework
- close #67
Remaining work
- include tests on CIs (see #69)
- add SOILWAT2 relevant tests (see #19)
> Feature add gtest

- generic.c
- `LogError` writes to R console only if `fp` file pointer is not null
- this is a mechanism to implement quiet runs
> Bugfix 88 rSOILWAT2

- SW_Carbon.c
- SW_Defines.h
- SW_Flow.c
- SW_Flow_lib.c
- SW_Flow_lib.h
- SW_Output.c
- SW_Output_mock.c
- SW_Site.c
- SW_Site.h
- SW_SoilWater.h
- SW_VegEstab.c
- SW_VegProd.c
- SW_VegProd.h
- test/test_SW_Carbon.cc
- test/test_SW_VegProd.cc
- close #135 
- vegetation type related variables are now arrays
- pre-defined macro loops for easier coding:
* ForEachVegType
* ForEachVegTypeBottomUp
> Feature VegArrays

- SW_Output.c
Addresses issue https://github.com/DrylandEcology/STEPWAT2/issues/109
- fix so that `p` [=months] is no longer incremented for each soil layer in `get_transp`
- fix so that `get_transp` no longer writes yearly transpiration values into a `STEPWAT2` array for month x soil layer
- guarantees that `get_transp` writes only monthly transpiration values the `STEPWAT2` array for month x soil layer
> Bugfix 109 stepwat2

- test/sw_testhelpers.cc
- addressing issue #205, but not completely resolving it
- added call to `SW_CTL_clear_model` before re-initializing SOILWAT2
- this is similar behavior to updated functions `start` of `rSOILWAT2` and `SXW_Reset` of `STEPWAT2`
> Clean memory in function `Reset_SOILWAT2_after_UnitTest`

- .gitmodules
- .travis.yml
- README.md
- SW_Output_mock.c
- makefile
- address (but not resolve) issues #206 and #208
- adjustments so that the `clang` compiler works
* set submodule `googletest` to specific commit 
* specify specific warnings in the `makefile` to be ignored (instead of propagated to errors)
> Bugfix 206

- SW_Markov.c
- SW_Model.c
- rands.c
In SW_Markov.c:
markov pcg rng now declared and seeded here. If used in other programs like STEPWAT2 it should be externed.
In SW_Model.c:
Removed declaration of markov pcg rng. declaration now in SW_Markov.c.
In rands.c:
Added ifdef RSOILWAT case to RandUni()
Removed reference to RAND_FAST which is now obsolete. 
Changed documentation to better explain RandSeed to SOILWAT and STEPWAT users.
> Addressed comments on pcg rng integration in pull request #233

- test/test_SW_Flow_Lib.cc
- test/test_SW_Flow_lib_temp.cc
- test/test_rands.cc
Each test that calls a random function now has its own pcg32_random_t RNG. The RNG is then seeded with a 0 so that the output will always be different.
> Added pcg rngs to gtests. (issue #237)

- SW_SoilWater.c
Addressing issue#231.
* Note that this will decrease code coverage slightly as this issue is related to a `CONSTANT` value not being visible.
> Divide by zero bug fix, issue #231

- SW_SoilWater.c
Reverts DrylandEcology/SOILWAT2#242 because I mistakenly merged into master before it was reviewed and Daniel does not think this branch is useful.
> Revert "Divide by zero bug fix, issue #231"

- README.md
- many_test_runs.sh
- test/test_SW_Flow_lib_temp.cc
This fixes the problem but is a hack so while it fixes this so our CIs pass, further investigation is necessary for a more permanent fix later on. This just changes the random number lower bound for `bDensity2[i]` from `.1` to `.129`. It still generates the value of `bDensity2[i]` randomly.
> Bugfix#210 intermittent fails

- README.md
- SW_Site.c
- SW_SoilWater.c
- test/test_SW_SoilWater.cc
close #231
- function `SW_SWCbulk2SWPmatric`:
* improved documentation about expectations
* added checks against 0 and NaN of the term "(theta / theta(saturated)) ^ b" --> new possibility for fatal error
- function `_read_layers`
* added checks to guarantee that soil layer width is > 0
- function `water_eqn`
* added checks to guarantee that theta(saturated) is > 0
- unit tests `SWSWCbulk2SWPmatric`
* improved documentation
* removed nonsensical tests
* added several tests to check that 0 < wilting point < field capacity is maintained
* added tests for edge cases of gravel fraction, theta(sat), and layer width
- unit tests `SWSWCbulk2SWPmatricDeathTest`
* improved documentation
* removed nonsensical tests
* added test for new fatal error if term "(theta / theta(saturated)) ^ b" becomes  0 …
> Update error handling in `SW_SWCbulk2SWPmatric`

- SW_Output.c
- SW_Output.h
- SW_Output_get_functions.c
- SW_Output_mock.c
- SW_VegProd.h
- testing/Input/outsetup.in
- corrected output when run with `STEPWAT2`
- new output target `BIOMASS` provides output for
* cover (%) for trees, shrubs, forbs, grasses
* biomass (g/m2 as component of total) for total, trees, shrubs, forbs, grasses, and litter
* live biomass (g/m2 as component of total) total, trees, shrubs, forbs, grasses
--> user visible change to the input file `outsetup.in` which gained a new row!
> Enhancement 262 biomassunits

- SW_Flow_lib.c
- SW_Flow_lib.h
- SW_Site.c
- SW_Site.h
- testing/Input/soils.in
- clearly differentiate the soil density of the whole soil (i.e, including the rock/gravel component) from the soil density of the < 2 mm fraction (i.e., matric component)
- no code changes
> Update documentation & comments for soil density

- SW_Site.h
- makefile
- commit 7272805a75a0653862410537a657b5328439669b (Nov 13, 2020) introduced several new functions including `nlayers_bsevap()` -- however, the declaration did not include the `void` argument which the definition later uses
- this commit is fixing this by adding `void` as the argument to the declaration
- to prevent future such cases, the severe tests are now using `-Wstrict-prototypes` (for the C compilations -- as this is not a valid warning under C++)
> Fix declaration of function `nlayers_bsevap()`

- SW_Output_get_functions.c
Provides a bug fix for [issue #194](https://github.com/DrylandEcology/rSOILWAT2/issues/194) on rSOILWAT side
- Fixes output order of array that is used when rSOILWAT is defined
- Order is now (of increasing indices): max, min, avg, max, min, avg
> Bugfix rSOILWAT2 issue194

- SW_Site.c
- SW_Site.h
- doc/Doxyfile
- test/sw_testhelpers.cc
- test/test_SW_Site.cc
- testing/Input/siteparam.in
- close #280 (Soil density: input either for < 2 mm fraction or for whole soil)
* new behavior: user specifies whether input soil density represents matric or bulk density; code then determines both matric and bulk density values from inputs
* previous behavior: input soil density was treated as matric density and converted to bulk density
> Specify type of soil density inputs

- .github/workflows/main_nix.yml
- .github/workflows/main_win.yml
- include/SW_Main_lib.h
- makefile
- src/SW_Main.c
- src/SW_Main_lib.c
- src/filefuncs.c
- tests/gtests/sw_maintest.cc
- tests/gtests/sw_testhelpers.cc
- tests/gtests/test_SW_Flow_lib_temp.cc
- tests/gtests/test_SW_Markov.cc
- tests/gtests/test_SW_Site.cc
- tests/gtests/test_SW_SoilWater.cc
- tests/gtests/test_SW_VegProd.cc
- tests/gtests/test_SW_Weather.cc
- close https://github.com/DrylandEcology/SOILWAT2/issues/342
* #342 is a bug for SOILWAT2 tests but not for other setups
- new approach for SOILWAT2 tests to close log files
* immediately close the `logfp` file connection that was created by `SW_F_read()`
* set `logfp` to NULL to silence non-error messages during tests
* update `LogError()` to behave as it already does for rSOILWAT2, i.e., if silenced, write only if error (message is sent to stderr) and otherwise write all message to `logfp` as previously
* DeathTests now expect a specific error message
> Bugfix too many open files

- include/SW_Flow_lib.h
- include/SW_SoilWater.h
- include/SW_datastructs.h
- src/SW_Control.c
- src/SW_Flow.c
- src/SW_Flow_lib.c
- src/SW_Site.c
- src/SW_SoilWater.c
- tests/gtests/test_SW_Flow_lib_temp.cc
re-organized initialization of soil temperature values: `SW_ST_setup_run()` now sets all soil temperature to initial values (which is only called if the soil temperature module is activated), i.e., both `SW_SoilWater.avgLyrTemp[]` and `SW_StRegValues.oldavgLyrTempR[]` are derived from `SW_Site.avgLyrTempInit[]`
> Feature soil temperature initialization

- .LSAN_suppr.txt
- NEWS.md
- include/SW_Control.h
- include/SW_Site.h
- src/SW_Control.c
- src/SW_Main.c
- src/SW_Site.c
- src/SW_SoilWater.c
- src/Times.c
- tests/gtests/sw_maintest.cc
- tests/gtests/sw_testhelpers.cc
- tests/gtests/sw_testhelpers.h
- tests/gtests/test_SW_Carbon.cc
- tests/gtests/test_SW_Defines.cc
- tests/gtests/test_SW_Flow_Lib.cc
- tests/gtests/test_SW_Flow_Lib_PET.cc
- tests/gtests/test_SW_Flow_lib_temp.cc
- tests/gtests/test_SW_Markov.cc
- tests/gtests/test_SW_Site.cc
- tests/gtests/test_SW_SoilWater.cc
- tests/gtests/test_SW_VegEstab.cc
- tests/gtests/test_SW_VegProd.cc
- tests/gtests/test_SW_Weather.cc
- tests/gtests/test_Times.cc
- tests/gtests/test_WaterBalance.cc
- tests/gtests/test_generic.cc
- tests/gtests/test_rands.cc
- tools/check_SOILWAT2.sh
- fix memory issues (close #205, close #356)
- `SW_SIT_init_run()` does not need argument `PATH_INFO *PathInfo`
- Reorganized tests
- only use test fixtures where really needed
- do not use test fixtures in death tests
- new class "AllTestStruct" that behaves just like "AllTestFixture" but does not inherit from `::testing::Test` -- which can be used in death tests
- place all relevant code inside `EXPECT_DEATH` in a compound statement -- code will otherwise be run twice (including the creation of test fixtures or constructing of a local copy of "AllTestStruct")
- tool "check_SOILWAT2.sh" now runs additional steps with the `leaks` command
> Feature memory fixes

- include/SW_Defines.h
- include/SW_datastructs.h
- include/rands.h
- makefile
- src/SW_Markov.c
- src/rands.c
- tests/gtests/test_SW_Flow_Lib.cc
- tests/gtests/test_SW_Flow_Lib_PET.cc
- tests/gtests/test_SW_Flow_lib_temp.cc
- tests/gtests/test_SW_Markov.cc
- tests/gtests/test_rands.cc
- new type "sw_random_t"
** for rSOILWAT2 defined as "int" (but unused)
** for SOILWAT2 and STEPWAT2 defined as "pcg32_random_t" (as previously)
- "pcg_basic.h" header now only included by "SW_Defines.h" (for typedef) and by "rands.c" (function calls) -- and only if not rSOILWAT2 -> makefile has new target "libr" to build library without pcg (for rSOILWAT2)
- close #373 "rSOILWAT2 does not use PCG for random numbers - remove requirement on its presence"
> Encapsulate RNG variable in dedicated type

- .github/workflows/main_nix.yml
- NEWS.md
- include/SW_Defines.h
- include/SW_datastructs.h
- include/SW_netCDF.h
- makefile
- src/SW_Main.c
- src/SW_Output.c
- src/SW_netCDF.c
Convert output to user requested units (#392)
> Feature nc units

- src/SW_netCDF.c
- Hard-code the units each input variables within the file `SW2_netCDF_output_variables.tsv`
- This will eliminate the chance that the user will input an incorrect unit under the "SW2 Units" column
- See #408
> Feature Hard-Code netCDF Input Variable Units

- NEWS.md
- include/SW_Main_lib.h
- include/SW_datastructs.h
- include/SW_netCDF.h
- src/SW_Control.c
- src/SW_Main.c
- src/SW_Main_lib.c
- src/SW_netCDF.c
- tests/gtests/sw_maintest.cc
- tests/gtests/sw_testhelpers.cc
- tests/gtests/sw_testhelpers.h
- Fix memory leak in nc-based test program: test's `main()` now checks for success of setup and, on failure, skips running tests and cleans up resources
- Option for automatic naming of domain template netCDF file (and avoiding early end of program)
- Simulation program via command line option `"-r"`
- Test program activates this option (and no longer fails if compiled with `SWNETCDF` flag if "domain.nc" didn't previously exist on path)
> Bugfix test memory leak

- include/SW_datastructs.h
- src/SW_netCDF.c
- tests/example/Input_nc/desc_nc.in
- In the latest version of SOILWAT2 (v8.0.0), when the user creates a large domain, there is a noticeable increase in the runtime of individual simulations
- SOILWAT2 now makes use of
- Custom nc chunking
- A new user input - `deflateLevel`
- An initial write to all output nc files while creating them
- See #425 for more information
> Fix increasing write times with nc outputs

- src/SW_Control.c
- src/SW_netCDF.c
- In SOILWAT2 v8.0.0, there is a bug where the two functions - `SW_NC_write_output()` & `SW_NC_read_out_vars()` - upon error, the open file does not get closed
- The mentioned two functions now close files upon failure before leaving the function
- See #424 and #426
> Close open files on error within `SW_netCDF.c`

- .github/workflows/main_nix.yml
- NEWS.md
- README.md
- doc/additional_pages/A_SOILWAT2_user_guide.md
- makefile
- tools/check_functionality.sh
- tools/rscripts/Rscript__SW2_output_txt_vs_r_vs_nc.R
- tools/run_iwyu.sh
- tools/run_tidy.sh
Simplify compilation of nc-based SOILWAT2 to `make CPPFLAGS=-DSWNC`
> Feature flag SWNC
