- SW_R_lib.c
Fixes Burke-Lauenroth-Lab/SoilWat_R_Wrapper#37
> Trying to fix Burke-Lauenroth-Lab/SoilWat_R_Wrapper#37

- SW_Flow.c
- SW_Flow_lib.c
- SW_Output.h
- SW_SoilWater.h
Fixes the code to determine if a constant in the Parton equation 2.21 is invalid and would thus cause extreme soil temperature values
> Temp error

- .travis.yml
- README.md
- makefile
- using travis-ci
- added travis-ci badge to README
> Feature add travisCI

- SW_Weather.c
- close https://github.com/Burke-Lauenroth-Lab/rSOILWAT2/issues/93
> Fix 'onSet_WTH_DATA': correctly check for missing values

- README.md
- SW_Carbon.c
- SW_Control.c
- SW_Files.c
- SW_Flow_lib.c
- SW_Output.c
- SW_Site.c
- SW_SoilWater.c
- generic.h
- makefile
- close #107
- debug print statements are only compiled if we compile with -DSWDEBUG
and then the print statements are only printed if the local debug
variable is set to a non-zero value
> Wrap debug code in ifdef SWDEBUG directives

- SW_Flow_lib.c
- SW_Flow_lib.h
- test/test_WaterBalance.cc
Close the water balance also if soil temperature is simulated and soil layers freeze
> Bugfix 133part2

- SW_Carbon.c
> Update comment referencing CO2 multiplier initialization

- SW_Site.c
- SW_VegProd.c
- close #179
- beautify report on updated fractions of vegetation components, evaporation coefficients, and transpiration coefficients
> Fix vegetation names in `logfile` report

- SW_Flow_lib.c
- test/test_SW_Flow_lib_temp.cc
- test/test_SW_Site.cc
#Issue 176
*deleted unnecessary messages
* testing EXPECT_DEATH_IF_SUPPORTED
*seperate unit tests for death tests ("TEST()")
> Fixes pertaining to Issues 174 & 176

- README.md
- makefile
easier debugging with specific make targets
> Feature debug

- SW_SoilWater.c
- test/test_SW_SoilWater.cc
Merge SW_SoilWater unit tests into master
> Merge SW_SoilWater unit tests into master

- rands.c
- rands.h
RandUniRange is now split into two functions; one to return a float and one to return and int. For more documentation see issue #234.
> Enhancement 234 chaukap

- .gitmodules
- SW_Markov.c
- SW_Model.c
- makefile
- rands.c
- rands.h
- test/test_SW_Flow_Lib.cc
- test/test_SW_Flow_lib_temp.cc
- test/test_rands.cc
Switch to a modern random number generator which allows multiple streams. We chose `PCG` (http://www.pcg-random.org/) which 
> is a family of simple fast space-efficient statistically good algorithms for random number generation
> Incorporate pcg rng

- SW_Files.h
correct number of files is 22 and not 23
> Fix `SW_NFILES`

- generic.h
- rands.c
- test/sw_testhelpers.h
addressing DrylandEcology/rSOILWAT2#132 and DrylandEcology/rSOILWAT2#133
> Bugfixes for rSOILWAT2

- SW_Flow.c
- SW_Flow_lib.c
- SW_Flow_lib.h
- SW_Sky.c
- SW_Sky.h
- SW_SoilWater.h
- SW_VegProd.c
- SW_VegProd.h
- SW_Weather.h
- doc/SOILWAT2.bib
- test/test_SW_Flow_Lib.cc
- testing/Input/climate.in
- testing/Input/veg.in
> Feature interception

- SW_Site.c
- SW_Site.h
- SW_VegProd.c
- SW_VegProd.h
- test/test_SW_Site.cc
- test/test_SW_VegProd.cc
I moved #268 from the branch `Bugfix_247_STEPWAT_compatability` to a dedicated branch so that we can test the new functionality easier and apply it across SOILWAT2 development without waiting for the gridded STEPWAT2 to finalize.
> Feature soillayerswap

- SW_Site.c
- SW_VegProd.c
- filefuncs.c
- generic.h
> Handle write attempts to NULL-file pointer correctly

- .travis.yml
- SW_Defines.h
- test/sw_testhelpers.h
- test/test_SW_Defines.cc
- tools/travis_update_binutils.sh
- previously, return true if argument was equal to `SW_MISSING`
- now, return true if argument is equal to `SW_MISSING` (as before) OR if argument is not finite, e.g., NaN, infinite
- this can be useful if weather data contains NaN values that have not been converted to `SW_MISSING` by the user
--> previously, NaN values in the weather data did not trigger the weather generator, instead the code aborted at some point with a cryptic error message
--> now, NaN values in the weather data are treated as missing and thus the weather generator is used to fill in those values
> Enhance `missing()`

- SW_Output.c
- SW_Output.h
- SW_Output_get_functions.c
- SW_Output_mock.c
- SW_SoilWater.h
- SW_VegProd.h
- testing/Input/outsetup.in
- tools/check_SOILWAT2.sh
Add total transpiration and evaporation components to "SW_AET" output type
- total transpiration (summed across soil layers and vegetation types) -- individual components available in "SW_TRANSP"
- evaporation from bare-soil (summed across soil layers) -- individual components available in "SW_EVAPSOIL"
- evaporation from canopy water (summed across vegetation types) -- individual components available in "SW_EVAPSURFACE"
- evaporation from surface water (sum of evaporation from litter-intercepted and ponded water) -- individual components available in "SW_EVAPSURFACE"
- evaporation from snowpack (sublimation) -- also available in "SW_PRECIP"
> Feature output et-components

- SW_Flow_lib.h
- SW_Site.c
- test/test_SW_Site.cc
- tools/check_SOILWAT2.sh
> Bugfix no negative soil coeffs

- SW_Flow.c
- SW_Flow_lib.c
- SW_Flow_lib.h
- SW_Output.c
- SW_Output.h
- SW_Output_get_functions.c
- SW_Output_mock.c
- SW_SoilWater.h
- test/test_SW_Flow_Lib.cc
- test/test_SW_Flow_lib_temp.cc
- testing/Input/outsetup.in
Added output for frozen data in soil layer files. Related to problems #278 and #141.
- see also https://github.com/DrylandEcology/rSOILWAT2/issues/101 and https://github.com/DrylandEcology/rSFSW2/issues/255
> New output: frozen status per soil layer

- .gitignore
- README.md
- new section on how to maintain reverse-dependencies STEPWAT2 and rSOILWAT2 while developing SOILWAT2
- attempt at a more friendly tone
- clarifications
> README: reverse dependencies

- NEWS.md
- SW_Markov.c
- SW_Weather.c
- SW_Weather.h
- doc/SOILWAT2.bib
- rands.c
- rands.h
- test/test_SW_Flow_Lib.cc
- test/test_SW_Flow_lib_temp.cc
- test/test_SW_Markov.cc
- test/test_rands.cc
- testing/Input/weathsetup.in
* random number generator produce sequences that can be exactly reproduced (via "initstate" and "initseq")
* close #326
> Feature pcg seeding

- SW_Flow_lib.c
- doc/Doxyfile
- doc/doxygen_exceptions.txt
- rands.c
- tools/run_doxygen.sh
> Feature fix make doc

- include/SW_Flow_lib_PET.h
- include/SW_Weather.h
- src/SW_Flow.c
- src/SW_Flow_lib_PET.c
- src/SW_Weather.c
- tests/example/Input/weathsetup.in
- tests/gtests/test_SW_Flow_Lib_PET.cc
- tests/gtests/test_SW_Weather.cc
- tests/gtests/test_WaterBalance.cc
- process daily radiation inputs if presence
- handle different specifications of radiation inputs
- utilize observed daily radiation if available
- estimate cloud cover from both observed and expected daily radiation
> Feature observed solar radiation

- src/SW_Carbon.c
- src/SW_Control.c
- src/SW_Files.c
- src/SW_Flow.c
- src/SW_Flow_lib.c
- src/SW_Flow_lib_PET.c
- src/SW_Main.c
- src/SW_Main_lib.c
- src/SW_Markov.c
- src/SW_Model.c
- src/SW_Output.c
- src/SW_Output_outarray.c
- src/SW_Output_outtext.c
- src/SW_Site.c
- src/SW_Sky.c
- src/SW_SoilWater.c
- src/SW_VegEstab.c
- src/SW_VegProd.c
- src/SW_Weather.c
- src/filefuncs.c
- src/mymemory.c
- src/rands.c
- tests/gtests/sw_testhelpers.cc
- Extends https://github.com/DrylandEcology/SOILWAT2/pull/367
- Properly handles a thrown error
- Provides premature function exiting when an error is encountered
- Guarantee memory will be freed and files are closed upon error
- Addresses https://github.com/DrylandEcology/SOILWAT2/issues/359
> Feature Individual Error Handling

- NEWS.md
- README.md
- include/SW_Control.h
- include/SW_Domain.h
- include/SW_datastructs.h
- src/SW_Control.c
- src/SW_Domain.c
- src/SW_Model.c
- src/SW_SoilWater.c
- tests/example/Input/domain.in
- tests/gtests/sw_testhelpers.h
- tests/gtests/test_SW_SpinUp.cc
- tests/gtests/test_WaterBalance.cc
- tools/plot__SW2_SpinupEvaluation.R
SpinUp feature functionality. 
Addreses #379.
> Feature SpinUp

- doc/Doxyfile
- doc/doxygen-awesome-css/LICENSE
- doc/doxygen-awesome-css/README.md
- doc/doxygen-awesome-css/doxygen-awesome-darkmode-toggle.js
- doc/doxygen-awesome-css/doxygen-awesome-fragment-copy-button.js
- doc/doxygen-awesome-css/doxygen-awesome-interactive-toc.js
- doc/doxygen-awesome-css/doxygen-awesome-paragraph-link.js
- doc/doxygen-awesome-css/doxygen-awesome-sidebar-only-darkmode-toggle.css
- doc/doxygen-awesome-css/doxygen-awesome-sidebar-only.css
- doc/doxygen-awesome-css/doxygen-awesome-tabs.js
- doc/doxygen-awesome-css/doxygen-awesome.css
Theme developed by doxygen-awesome-css
https://github.com/jothepro/doxygen-awesome-css
Installation: "manually copying the files" v2.3.3
> Beautify doxygen-generated documentation

- doc/additional_pages/code_contribution_guidelines.md
- makefile
- src/SW_Main_lib.c
- tools/check_outputModes.sh
- tools/rscripts/Rscript__SW2_output_txt_vs_r_vs_nc.R
- Fix makefile for user provided flags for netcdf-c, udunits2, and expat
- sw_print_version() now prints capabilities
- Improve tools/check_outputModes.sh: information on which of the output modes succeeded and which ones failed
> Fix compile nc
